### ISSUE TITLE
Add this plugin to rockerBOO nvim plugins list

### ISSUE THREAD

**Issue by AlexisFinnZest** [dzfrias/arena.nvim#13]
I really like your plugin, it's pretty much what I was looking for in a buffer manager/switcher.
Would be cool to add it to rockerBOO's plugin list, as for me at least it does something that I wasn't quite able to replicate with other plugins.
https://github.com/rockerBOO/awesome-neovim
Anyway, thanks for the cool plugin.

**Comment by dzfrias** [comment]
Thanks for your suggestion! It just got merged!
