### ISSUE TITLE
Session awareness

### ISSUE THREAD

**Issue by sjudin** [dzfrias/arena.nvim#2]
Hi,

I was fiddling around with this plugin and it seems great! One thing that I am missing is project/session awareness. ie that if I switch between sessions using for example, [possession.nvim](https://github.com/jedrzejboczar/possession.nvim) then I want to have session-specific items in my arena menu.

I would be up for a discussion regarding how to implement this feature, a first approach might be to look for usual project root patterns (.git, compile_commands etc) and only update/show the most frequently visited buffers which are children of that root pattern.

Thanks for the plugin! :)

**Comment by dzfrias** [comment]
Thanks! Session awareness sounds like a great idea!

That's a good idea. We could keep track of different buffers across projects (identified with root patterns). Alternatively, we could try to integrate directly with session managers, but there's a bunch of those and that seems pretty rigid.

Another interesting question is if we make this the default behavior. I think some might get confused if they expect a buffer switcher but it's filtered per-project. Anyway, I don't think this would be too hard to write, and it'd be a nice opt-in feature.

**Comment by dzfrias** [comment]
For sure. I'll see if I can implement this at some point!

**Comment by dzfrias** [comment]
Done as of e921e9f!
