### ISSUE TITLE
[feature request] provide some basic keybindings

### ISSUE THREAD

**Issue by gipo355** [dzfrias/arena.nvim#4]
Hey again! 

Loving this plugin. Esc close made this 2x better for me since i swapped esc and caps.

Dropping in some things i wish i had when using it

## Feature 1:

**delete entry**

Another thing that would be really useful would be deleting one item from the list (dd maybe)?

Sometimes i open things by mistake and they get to clutter the list. Removing them quickly with dd or ctrl+d would be cool

at the moment to do it i have to enter the file and close it to get it removed. possible to close it from arena maybe similar to telescope buffers ctrl+d?

## feature 2: 

**pinning one item to the top**

sometimes i really want to have 1 file as a pivot point. 

I jump between 3 files imported in my pivot file and would like to access it quickly at the top

Would it be possible to provide a key to " toggle pin" at the top?

**Comment by dzfrias** [comment]
I like these ideas! I'll work on implementing both of these features! Deleting entries is definitely something that I'd like, as well.

**Comment by dzfrias** [comment]
`d` is now bound to `require("arena").remove(...)`! I'll work on pinning, too!

**Comment by dzfrias** [comment]
I added the `p` keybind, for `require("arena").pin(...)`!
