### ISSUE TITLE
[feature] going up from line 1: move cursor to last item

### ISSUE THREAD

**Issue by gipo355** [dzfrias/arena.nvim#6]
the same for going down from last item: move to first item

**Comment by dzfrias** [comment]
Hmm, I'm not sure about adding this as the default behavior. I think something like this can be accomplished pretty easily by just a simple keybind or two.

```lua
-- In config
keybinds = {
    ["j"] = function()
      local line, _ = unpack(vim.api.nvim_win_get_cursor(0))
      if line == vim.api.nvim_buf_line_count(0) then
        vim.fn.cursor(1, 0)
      else
        vim.fn.cursor(line + 1, 0)
      end
    end,
}
```

Something similar could be done for "k"

**Comment by gipo355** [comment]
Yes, maybe it would be a change from nvim default pattern.

I was trying to think of a way to increase accessibility on like 5 items since this is what I frequently have up.

Having bound arena to c-k, this would speed up last and second last access without using shift or number to reduce wrist torque.

Another thing I thought of for this case was to maybe bind jkl; to line 1 2 3 4 directly and use c-l c-k to move up and down while highlighting each line differently

**Comment by gipo355** [comment]
```lua
{
                    ["j"] = function()
                        local line, _ = unpack(vim.api.nvim_win_get_cursor(0))
                        if line == vim.api.nvim_buf_line_count(0) then
                            vim.fn.cursor(1, 0)
                        else
                            vim.fn.cursor(line + 1, 0)
                        end
                    end,
                    ["k"] = function()
                        local line, _ = unpack(vim.api.nvim_win_get_cursor(0))
                        if line == 1 then
                            vim.fn.cursor(vim.api.nvim_buf_line_count(0), 0)
                        else
                            vim.fn.cursor(line - 1, 0)
                        end
                    end,
                }
```

this will do for now thanks!
