### ISSUE TITLE
Keybinding with action

### ISSUE THREAD

**Issue by adriafarres** [dzfrias/arena.nvim#7]
Hello! Thank you for your work on this plugin! I'm trying to define a keybinding like follows:

```lua
keybinds = {
    ['<c-s>'] = function()
      require('arena').action(function(bufnr, info)
        vim.cmd({
          cmd = 'split',
          args = { vim.fn.bufname(bufnr) },
          mods = { horizontal = true },
        })
        vim.fn.cursor(info.lnum, 0)
      end)
    end,
}
```

but it does not seem to work. What am I doing wrong?

Thank you

**Comment by dzfrias** [comment]
The `action()` function returns a function, if you remove the outer function that wraps your action call it should work!

**Comment by adriafarres** [comment]
Thank you! I had tried that as well and it didn't work until I used `config` instead of `opts` when using `lazy.nvim`.
